FROM node:20-slim

WORKDIR /app

# Instalar dependências necessárias para o desenvolvimento
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    make \
    g++ \
    build-essential \
    pkg-config \
    libcairo2-dev \
    libpango1.0-dev \
    libjpeg-dev \
    libgif-dev \
    librsvg2-dev \
    && rm -rf /var/lib/apt/lists/*

# Copiar arquivos de configuração de dependências
COPY package*.json ./

# Configuração para desenvolvimento
ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

# Instalar dependências
RUN npm install

EXPOSE 3000

# Comando para desenvolvimento
CMD ["npm", "run", "dev"] 